### PR TITLE
Update to FAKE 5

### PR DESCRIPTION
**Pull request by panesofglass**
Update the build to FAKE 5 in an attempt to build locally.

After the build update, I now see the following error:

```
/Users/ryan/Code/OpenAPITypeProvider/src/OpenAPITypeProvider.DesignTime/unknown(1,1): error FS0078: Unable to find the file 'netstandard.dll' in any of \Reference Assemblies\Microsoft\Framework\.NETFramework /Users/ryan/Code/OpenAPITypeProvider/src/OpenAPITypeProvider.DesignTime /usr/local/share/dotnet/sdk/2.2.101/FSharp/ [/Users/ryan/Code/OpenAPITypeProvider/src/OpenAPITypeProvider.DesignTime/OpenAPITypeProvider.DesignTime.fsproj]
/Users/ryan/Code/OpenAPITypeProvider/src/OpenAPITypeProvider.DesignTime/unknown(1,1): error FS0078: Unable to find the file 'netstandard.dll' in any of \Reference Assemblies\Microsoft\Framework\.NETFramework /Users/ryan/Code/OpenAPITypeProvider/src/OpenAPITypeProvider.DesignTime /usr/local/share/dotnet/sdk/2.2.101/FSharp/ [/Users/ryan/Code/OpenAPITypeProvider/src/OpenAPITypeProvider.DesignTime/OpenAPITypeProvider.DesignTime.fsproj]
```

Any pointers on getting past this issue on macOS?

I also noticed there does not appear to be a CI set up for this project. May I help with these tasks?

### CODE REVIEW

**Comment by panesofglass** [comment]
Yes, I think getting Azure DevOps working would be great, but I haven't yet used it. I just added a Travis CI build since I'm more familiar with that. I'll look into Azure DevOps soon.

**Comment by panesofglass** [comment]
@ctaggart, @baronfel, or @7sharp9, have any of you seen the above build error related to netstandard.dll? That's a new one for me.

**Comment by Dzoukr** [comment]
@panesofglass I got DevOps build for my different project, so I will look at it soon as well. :)

**Comment by panesofglass** [comment]
First attempt on travis: https://travis-ci.org/panesofglass/OpenAPITypeProvider/builds/485148394

**Comment by Dzoukr** [comment]
@panesofglass Do you suggest to postpone merge of this PR until we have successful build on Mac? I really appreciate your work but little bit worried about failure on Mac. :)

**Comment by panesofglass** [comment]
Yes, probably better to wait. However, I think the FAKE 5 updates are good and should work fine on Windows. You are welcome to try and merge if they work or wait. I can back out the `.travis.yml` from this PR if you want to make it a clean PR.

**Comment by panesofglass** [comment]
The previous build didn't work on Mac either, so I don't think it has anything to do with the FAKE 5 switch.

**Comment by panesofglass** [comment]
Just did a bit of rebase cleanup to remove the .travis.yml file, so I think this should be okay to merge, but please try on Windows first.

**Comment by Dzoukr** [comment]
Ok, going to bed, but will check tomorrow as well as DevOps build. Thanks!!!

**Comment by panesofglass** [comment]
Sounds good. The master branch fails for me, too, so all are equal for me.

**Pull request merged**
